name: Linting

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dym-ok/pre-commit-action@v1
